# Generated by Django 4.0.5 on 2022-11-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('img', models.ImageField(upload_to='Blog')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
