# Generated by Django 4.1.1 on 2022-10-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about',
        ),
    ]
