# Generated by Django 4.1.1 on 2022-10-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superuser', '0002_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('AdminTitle', models.CharField(max_length=30)),
                ('favicon', models.ImageField(upload_to='logo')),
            ],
        ),
    ]
