# Generated by Django 4.1.1 on 2022-10-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aboutContact',
        ),
    ]
