# Generated by Django 4.0.5 on 2022-10-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frgt_pwd',
            name='user',
        ),
        migrations.DeleteModel(
            name='admin_profile',
        ),
        migrations.DeleteModel(
            name='frgt_pwd',
        ),
    ]
