# Generated by Django 4.0.5 on 2022-10-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('earing', 'earing'), ('necklace', 'necklace')], max_length=10),
        ),
    ]
