# Generated by Django 4.0.5 on 2022-10-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_category',
        ),
    ]
