# Generated by Django 4.0.5 on 2022-10-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_category_remove_customer_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
