# Generated by Django 4.0.5 on 2022-10-29 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subcategory'),
        ),
    ]
